<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Bogot D.C                           _c8b5ae</name>
   <tag></tag>
   <elementGuidId>9f52f7fe-facc-49f5-87de-5f1a04f295b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputState</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='inputState']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputState</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control controls</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        Bogotá D.C
                                        Medellín
                                        Calí
                                        Barranquilla
                                        Cartagena
                                        Bucaramanga
                                        Manizales
                                        Pereira
                                        Cúcuta
                                        Ibagué
                                        Valledupar
                                        Boyáca
                                        Pasto
                                        Armenia
                                        Villavicencio
                                        Neiva
                                        Popayán
                                        Armenia
                                    </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputState&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='inputState']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciudad'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N. Contacto'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Introduce una contraseña'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmar contraseña'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'inputState' and @type = 'text' and @name = 'city' and (text() = '
                                        Bogotá D.C
                                        Medellín
                                        Calí
                                        Barranquilla
                                        Cartagena
                                        Bucaramanga
                                        Manizales
                                        Pereira
                                        Cúcuta
                                        Ibagué
                                        Valledupar
                                        Boyáca
                                        Pasto
                                        Armenia
                                        Villavicencio
                                        Neiva
                                        Popayán
                                        Armenia
                                    ' or . = '
                                        Bogotá D.C
                                        Medellín
                                        Calí
                                        Barranquilla
                                        Cartagena
                                        Bucaramanga
                                        Manizales
                                        Pereira
                                        Cúcuta
                                        Ibagué
                                        Valledupar
                                        Boyáca
                                        Pasto
                                        Armenia
                                        Villavicencio
                                        Neiva
                                        Popayán
                                        Armenia
                                    ')]</value>
   </webElementXpaths>
</WebElementEntity>
